name: Build Nightly package (test)

on:
  push:
    branches:
      - 'new_build_image_test-xxx'

jobs:
  build_linux:
    strategy:
      matrix:
        configuration: [FastDebug, Release]
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: arm64
    name: Linux
    runs-on: ${{ matrix.os }}
    container: ghcr.io/scp-fs2open/linux_build:sha-ab87451
    steps:
      - uses: actions/checkout@v7
        name: Checkout
        with:
          submodules: true
      - name: Set workspace as safe
        # This appears to be broken in current actions, so do it manually
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Configure CMake
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: gcc-9
          ENABLE_QTFRED: OFF
        run: $GITHUB_WORKSPACE/ci/linux/configure_cmake.sh
      - name: Compile
        working-directory: ./build
        env:
          CONFIGURATION: ${{ matrix.configuration }}
        run: |
          LD_LIBRARY_PATH=$Qt5_DIR/lib:$LD_LIBRARY_PATH ninja -k 20 all
      - name: Run Tests
        working-directory: ./build
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          XDG_RUNTIME_DIR: /root
        run: $GITHUB_WORKSPACE/ci/linux/run_tests.sh
      - name: Generate AppImage
        working-directory: ./build
        env:
          CONFIGURATION: ${{ matrix.configuration }}
        run: $GITHUB_WORKSPACE/ci/linux/generate_appimage.sh $GITHUB_WORKSPACE/build/install
      - name: Upload build result
        uses: actions/upload-artifact@v7
        with:
          name: linux-${{ matrix.configuration }}-${{ matrix.arch }}
          path: ${{ github.workspace }}/build/install/*.AppImage
  linux_zip:
    name: Build Linux distribution zip
    needs: build_linux
    runs-on: ubuntu-latest
    container: ghcr.io/scp-fs2open/sftp_upload:sha-ab87451
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - uses: actions/checkout@v7
        name: Checkout
        with:
          submodules: true
          fetch-depth: '0'
      - name: Set workspace as safe
        # This appears to be broken in current actions, so do it manually
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Download Release builds
        uses: actions/download-artifact@v8
        with:
          name: linux-Release-${{ matrix.arch }}
          path: builds
      - name: Download FastDebug builds
        uses: actions/download-artifact@v8
        with:
          name: linux-FastDebug-${{ matrix.arch }}
          path: builds
      - name: Fix permissions
        working-directory: ./builds
        shell: bash
        run: chmod 755 *.AppImage
      - name: Create Distribution package
        working-directory: ./builds
        env:
          ARCH: ${{ matrix.arch }}
        run: $GITHUB_WORKSPACE/ci/linux/create_dist_pack.sh Linux
      - name: Upload result package
        working-directory: ./builds
        env:
          INDIEGAMES_USER: ${{ secrets.INDIEGAMES_USER }}
          INDIEGAMES_SSHPASS: ${{ secrets.INDIEGAMES_PASSWORD }}
          DATACORDER_USER: ${{ secrets.DATACORDER_USER }}
          DATACORDER_SSHPASS: ${{ secrets.DATACORDER_PASSWORD }}
        run: $GITHUB_WORKSPACE/ci/linux/upload_dist_package.sh nightly
