name: Build Release package

on:
  workflow_dispatch:
  push:

env:
  QT_VERSION: 5.12.12

jobs:
  build_windows:
    strategy:
      matrix:
        configuration: [FastDebug, Release]
        arch: [Win32, x64, ARM64]
        include:
          - arch: [Win32, x64]
            simd: [SSE2, AVX]
    name: Windows
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v5
        # Checkout repo
        name: Checkout
        with:
          submodules: true
          ref: '${{ github.ref }}'
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: 1.4.304.1
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
      - name: Configure CMake
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          ARCHITECTURE: ${{ matrix.arch }}
          SIMD: ${{ matrix.simd }}
        shell: bash
        run: |
          mkdir build
          cd build

          if [ "$ARCHITECTURE" = "Win32" ]; then
              cmake -DCMAKE_INSTALL_PREFIX="$(pwd)/install" -DFSO_USE_SPEECH="ON" \
                  -DFSO_USE_VOICEREC="ON" -DFORCED_SIMD_INSTRUCTIONS="$SIMD" \
                  -DFSO_BUILD_QTFRED=OFF -DFSO_BUILD_TESTS=ON \
                  -DFSO_INSTALL_DEBUG_FILES="ON" -DFSO_BUILD_WITH_VULKAN="OFF" -A "$ARCHITECTURE" \
                  -G "Visual Studio 17 2022" -T "v143" -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
          else
              cmake -DCMAKE_INSTALL_PREFIX="$(pwd)/install" -DFSO_USE_SPEECH="ON" \
                  -DFSO_USE_VOICEREC="ON" -DFORCED_SIMD_INSTRUCTIONS="$SIMD" \
                  -DFSO_BUILD_QTFRED=OFF -DFSO_BUILD_TESTS=ON \
                  -DFSO_INSTALL_DEBUG_FILES="ON" -A "$ARCHITECTURE" \
                  -G "Visual Studio 17 2022" -T "v143" -DCMAKE_BUILD_TYPE=$CONFIGURATION ..
          fi
      - name: Compile
        working-directory: ./build
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        run: |
          cmake --build . --config "$CONFIGURATION" --target INSTALL -- /verbosity:minimal
          ls -alR "$(pwd)/install"
      - name: Run Tests
        working-directory: ./build
        env:
          CONFIGURATION: ${{ matrix.configuration }}
        shell: bash
        run: ./bin/$CONFIGURATION/unittests --gtest_shuffle
      - name: Set artifact id
        run: |
          id=
          if [ -n "${{ matrix.simd }}" ]; then
            id="${{ matrix.configuration }}-${{ matrix.arch }}-${{ matrix.simd }}"
          else
            id="${{ matrix.configuration }}-${{ matrix.arch }}"
          fi
          echo "artifact_id=${id}" >> $GITHUB_ENV
      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ env.artifact_id }}
          path: ${{ github.workspace }}/build/install/*
